[functions.webhook-processor-v2]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.webhook-recovery]
verify_jwt = false

[functions.evolution-sync-history]
verify_jwt = false

[functions.sync-contacts-on-connect]
enabled = true
verify_jwt = true
import_map = "./functions/sync-contacts-on-connect/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/sync-contacts-on-connect/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/sync-contacts-on-connect/*.html" ]
